# Generated by Django 5.2.1 on 2025-06-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0005_alter_control_confidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad_Domain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(db_index=True)),
                ("sid", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ad_domain",
                "verbose_name_plural": "ad_domain",
                "db_table": "ad_domain",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_ad_domain.name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ad_User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(db_index=True)),
                ("password", models.TextField(blank=True, null=True)),
                ("sid", models.TextField(blank=True, db_index=True, null=True)),
                ("fullname", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("enabled", models.BooleanField(blank=True, null=True)),
                ("pwd_last_set", models.IntegerField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("distinguished_name", models.TextField(blank=True, null=True)),
                ("sam_account_name", models.TextField(blank=True, null=True)),
                ("when_created", models.IntegerField(blank=True, null=True)),
                ("last_logon", models.IntegerField(blank=True, null=True)),
                ("last_logon_timestamp", models.IntegerField(blank=True, null=True)),
                ("admin_count", models.BooleanField(blank=True, null=True)),
                ("pwd_never_expires", models.BooleanField()),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_users",
                        to="cybsmodels.ad_domain",
                    ),
                ),
            ],
            options={
                "verbose_name": "ad_user",
                "verbose_name_plural": "ad_user",
                "db_table": "ad_user",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "domain"), name="unique_ad_user.name_domain"
                    )
                ],
            },
        ),
    ]
