# Generated by Django 5.2.1 on 2025-06-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0006_ad_domain_ad_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad_user",
            old_name="fullname",
            new_name="full_name",
        ),
    ]
