# Generated by Django 5.2.1 on 2025-06-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0007_rename_fullname_ad_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad_user",
            name="pwd_never_expires",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
