# Generated by Django 5.2.1 on 2025-06-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0008_alter_ad_user_pwd_never_expires"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad_Computer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(db_index=True)),
                ("sid", models.TextField(blank=True, db_index=True, null=True)),
                ("os", models.TextField(blank=True, null=True)),
                ("enabled", models.BooleanField(blank=True, null=True)),
                ("pwd_last_set", models.IntegerField(blank=True, null=True)),
                ("distinguished_name", models.TextField(blank=True, null=True)),
                ("sam_account_name", models.TextField(blank=True, null=True)),
                ("when_created", models.IntegerField(blank=True, null=True)),
                ("last_logon", models.IntegerField(blank=True, null=True)),
                ("last_logon_timestamp", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("primary_group_sid", models.TextField(blank=True, null=True)),
                ("dns_hostname", models.TextField(blank=True, null=True)),
                ("os_version", models.TextField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_computers",
                        to="cybsmodels.ad_domain",
                    ),
                ),
            ],
            options={
                "verbose_name": "ad_computer",
                "verbose_name_plural": "ad_computer",
                "db_table": "ad_computer",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "domain"), name="unique_ad_computer.name_domain"
                    )
                ],
            },
        ),
    ]
