# Generated by Django 5.2.1 on 2025-06-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0009_ad_computer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Smb_File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("share", models.TextField(db_index=True)),
                ("directory", models.TextField(db_index=True)),
                ("file", models.TextField(db_index=True)),
                ("size", models.IntegerField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smb_files",
                        to="cybsmodels.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "smb_file",
                "verbose_name_plural": "smb_file",
                "db_table": "smb_file",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service", "share", "directory", "file"),
                        name="unique_smb_file.service_share_directory_file",
                    )
                ],
            },
        ),
    ]
