# Generated by Django 5.2.1 on 2025-06-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0010_smb_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="smb_file",
            name="is_directory",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
