# Generated by Django 5.2.1 on 2025-06-04 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0011_smb_file_is_directory"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="smb_file",
            name="unique_smb_file.service_share_directory_file",
        ),
        migrations.RemoveField(
            model_name="smb_file",
            name="service",
        ),
        migrations.AddField(
            model_name="smb_file",
            name="host",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="smb_files",
                to="cybsmodels.host",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="smb_file",
            constraint=models.UniqueConstraint(
                fields=("host", "share", "directory", "file"),
                name="unique_smb_file.host_share_directory_file",
            ),
        ),
    ]
