# Generated by Django 5.2.1 on 2025-06-04 19:48

import cybsuite.cyberdb.django_orm.schema_to_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cybsmodels",
            "0012_remove_smb_file_unique_smb_file_service_share_directory_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad_computer",
            name="last_logon",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ad_computer",
            name="last_logon_timestamp",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ad_computer",
            name="pwd_last_set",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ad_computer",
            name="when_created",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ad_user",
            name="last_logon",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ad_user",
            name="last_logon_timestamp",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ad_user",
            name="pwd_last_set",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ad_user",
            name="when_created",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="nmap_confidence",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="port",
            field=models.BigIntegerField(
                db_index=True,
                validators=[
                    cybsuite.cyberdb.django_orm.schema_to_models.prett_id_validator
                ],
            ),
        ),
        migrations.AlterField(
            model_name="smb_file",
            name="size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
