# Generated by Django 5.2.1 on 2025-06-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0013_alter_ad_computer_last_logon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jucy_Search",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.TextField(db_index=True)),
                ("rule_value", models.TextField(db_index=True)),
                ("value", models.TextField(db_index=True)),
                ("category", models.TextField(db_index=True)),
            ],
            options={
                "verbose_name": "juicy_search",
                "verbose_name_plural": "juicy_search",
                "db_table": "juicy_search",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rule_name", "rule_value", "value", "category"),
                        name="unique_juicy_search.rule_name_rule_value_value_category",
                    )
                ],
            },
        ),
    ]
