# Generated by Django 5.2.1 on 2025-06-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0014_jucy_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="jucy_search",
            name="metadata",
            field=models.TextField(blank=True, null=True),
        ),
    ]
