# Generated by Django 5.2.1 on 2025-06-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0015_jucy_search_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="smb_file",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="smb_files", to="cybsmodels.ad_user"
            ),
        ),
    ]
