# Generated by Django 5.2.2 on 2025-06-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0016_smb_file_users"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Jucy_Search",
            new_name="Juicy_Search",
        ),
    ]
