# Generated by Django 5.2.2 on 2025-06-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0017_rename_jucy_search_juicy_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosts",
                to="cybsmodels.ad_domain",
            ),
        ),
    ]
