# Generated by Django 5.2.2 on 2025-06-11 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0018_host_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service_Smb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("smbv1", models.BooleanField(blank=True, null=True)),
                ("signign", models.BooleanField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_smbs",
                        to="cybsmodels.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "service_smb",
                "verbose_name_plural": "service_smb",
                "db_table": "service_smb",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service",), name="unique_service_smb.service"
                    )
                ],
            },
        ),
    ]
