# Generated by Django 5.2.2 on 2025-06-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0019_service_smb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service_smb",
            old_name="signign",
            new_name="signing",
        ),
    ]
