# Generated by Django 5.2.2 on 2025-06-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0020_rename_signign_service_smb_signing"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad_user",
            name="lm",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ad_user",
            name="ntlm",
            field=models.TextField(blank=True, null=True),
        ),
    ]
