# Generated by Django 5.2.3 on 2025-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0021_ad_user_lm_ad_user_ntlm"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="compromised",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
