# Generated by Django 5.2.1 on 2025-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0022_host_compromised"),
    ]

    operations = [
        migrations.AddField(
            model_name="windows_user",
            name="password",
            field=models.TextField(blank=True, null=True),
        ),
    ]
