# Generated by Django 5.2.1 on 2025-06-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0023_windows_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="windows_user",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="windows_users",
                to="cybsmodels.host",
            ),
        ),
    ]
