# Generated by Django 5.2.3 on 2025-06-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0024_alter_windows_user_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="compromised",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
