# Generated by Django 5.2.3 on 2025-06-15 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cybsmodels", "0025_alter_host_compromised"),
    ]

    operations = [
        migrations.AlterField(
            model_name="control",
            name="latest_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="controls",
                to="cybsmodels.run",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hosts",
                to="cybsmodels.ad_domain",
            ),
        ),
        migrations.AlterField(
            model_name="windows_user",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="windows_users",
                to="cybsmodels.host",
            ),
        ),
    ]
